### ISSUE TITLE
这项目是停更了吗？快1个月了没更新。。

### ISSUE THREAD

**Issue by arden** [mafanr/meq#98]
这项目是停更了吗？快1个月了没更新，有点着急啊。。。

**Comment by sunface** [comment]
你们急用还是？目前其实已经可以使用了，只不过还缺乏文档，我们会找时间把文档补上

**Comment by arden** [comment]
也不是，只是看到这么久一直没更新，以后这项目已经停止开发了，没有后续更新和维护，就不好用项目里。

**Comment by sunface** [comment]
近期会补充上文档，请关注官网哈，不会停更，我们最近还准备用meq来智能客服
